version: '2'
services:
  mongodb:
    image: mongo:3.4.3
    container_name: suw_mongo
    ports:
        - "27017:27017"
    restart: always
    volumes:
      - "../../mongo_data:/data/db"

  app:
    build: ./node-app
    container_name: suw_app
    depends_on:
      - mongodb
    restart: always
    volumes:
      - "./node-app:/api"
    ports:
      - 3000:3000
    environment:
      - COMPOSE_HTTP_TIMEOUT=200
